name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v3

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3.1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  test:
    runs-on: ubuntu-latest
    name: Test on project

    strategy:
      matrix:
        include:
          - repo-owner: binarycraft007
            repo-name: libcronet
            pkg-name: libcronet
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          path: action

      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo-owner }}/${{ matrix.repo-name }}
          path: ${{ matrix.repo-name }}

      - name: srcinfo
        uses: ./action
        with:
          target: srcinfo
          pkgname: ${{ matrix.repo-name }}/${{ matrix.pkg-name }}

      - name: pkgbuild
        uses: ./action
        with:
          target: pkgbuild
          pkgname: ${{ matrix.repo-name }}/${{ matrix.pkg-name }}
